### ISSUE TITLE
Needs Faster Mending for Diamond Tools

### ISSUE THREAD

**Issue by Marcnesium87** [legobmw99/BetterThanMending#12]

**Comment by TookUrSweetRoll** [comment]
I second the motion. Maybe a config to adjust the speed?

**Comment by Jaeiya** [comment]
I would also like to see this feature added. Modded tools can have upwards of 1000's of durability, which means it can take up to 3 minutes of holding down shift-right click to fully repair the tool.

Maybe have a separate keybind (shift+ctrl right click) that instantly uses the exact amount of XP to repair the tool and if you don't have enough, it just uses all your available XP to repair it as much as possible.

**Comment by legobmw99** [comment]
> Maybe have a separate keybind (shift+ctrl right click) that instantly uses the exact amount of XP to repair the tool and if you don't have enough, it just uses all your available XP to repair it as much as possible.

Not a terrible idea for how to implement this, but it would require a regression on the multiplayer side. See, the mod just recently changed so it can be installed only on the server. This is because both things it requires - crouching and right clicking - are communicated to the server, always. Other keyboard inputs like control would require making clientside non-optional again.

My biggest question has always been - is this a huge problem? Mending is pretty slow in vanilla as well, and I'm also more of a 'top up before it gets super low' kind of person with my tools, so I guess it's not often I mend a tool entirely from empty.

**Comment by Jaeiya** [comment]
> Mending is pretty slow in vanilla as well, and I'm also more of a 'top up before it gets super low' kind of person with my tools, so I guess it's not often I mend a tool entirely from empty.

You make a good point here; I have also been using the 'top off' method as much as possible, but even topping off something that has 1000's of durability can be tedious. It's hard to know when to top it off based on its durability progress bar, as 15% down could either mean 100 or 500 durability needing to be mended.

It's unfortunate that those are the only keybinds that the server registers solely; what about other mouse buttons, like the back or forward ones? I believe they are mouse 5/4 in the controls settings. But of course that alienates people who don't have a mouse with those buttons...even though they are very common these days.

**Comment by legobmw99** [comment]
Quick poll: which option is better:

1. The mod repairs your entire tool in one click, unless you don't have enough xp, in which case it drains all your xp to repair as much as it can.

2. The mod is 10x faster at repairing if you have enough xp, slowing back down to the current amount if you're low on xp or the tool is nearly fully repaired?

**Comment by Jaeiya** [comment]
I think option 2 is the best here, as it allows people with limited XP to ration it. However if people are willing to accept that they're using all their XP to mend a tool, then option 1 is acceptable to me. But as far as balance goes, I would choose option 2.
